services:
  app:
    build: .
    container_name: crm_app
    restart: unless-stopped
    environment:
      DATABASE_URL: ${CONTAINER_DATABASE_URL:-postgresql+psycopg://${CRM_DB_USER:-${POSTGRES_USER:-flowcrm}}:${CRM_DB_PASSWORD:-${POSTGRES_PASSWORD}}@postgres:5432/${CRM_DB_NAME:-${POSTGRES_DB:-flowcrm}}}
      APP_ENV: ${APP_ENV:-production}
      SECRET_KEY: ${SECRET_KEY:-change-this-secret-key-before-production}
    # ports:
    #   - "8000:8000"
    volumes:
      - ./backups:/app/backups
    networks:
      - web_network
      - postgres_network

networks:
  web_network:
    external: true
  postgres_network:
    external: true
